namespace bConnect.Variable {public enum Type{Unknown,Number,String,Date,Checkbox,Dropdownbox,DropdownListbox,Filelink,Folder,Password,Certificate}}
namespace bConnect.Variable {public enum Scope{Device,MobileDevice,Job,OrgUnit,Software,HardwareProfile,ICDevice,NetworkDevice,AndroidDevice,IOSDevice,WindowsPhoneDevice}}
namespace bConnect.Endpoint {public enum Type{Unknown=0,WindowsEndpoint=1,AndroidEndpoint=2,iOSEndpoint=3,MacEndpoint=4,WindowsPhoneEndpoint=5,NetworkEndpoint=16,IndustrialEndpoint=18}}
namespace bConnect.Endpoint {public enum Mode{LAN,Internet,Dynamic}}
namespace bConnect.Endpoint {public enum Channel{LAN,Internet,AutoLan,AutoInternet}}
namespace bConnect.Endpoint {public enum AgentState{Unchanged=-1,Unknown=0,NotInstalled=1,Running=3,Rebooting=4}}
namespace bConnect.Endpoint {public enum ManagementState{Unknown=0,Enrollable=1,Enrolling=2,Managed=3,Unmanaged=4}}
namespace bConnect.Endpoint {public enum Owner{Unknown=-2,Company=0,Private=1}}
namespace bConnect.Endpoint {public enum ComplianceCheckCategory{Active=0,Inactive=1,InactiveTemporarily=2}}
namespace bConnect.Endpoint {[System.Flags]public enum ClientOptions:uint{EnableOsInstall=0x00000001,InheritAutoInstallation=0x00000002,EnableAUT=0x00000100,EnableEnergyManagement=0x00000200,Deactivated=0x80000000}}
namespace bConnect.Endpoint {public enum PrimaryUserOptions:uint{Initial=0x00000000,NotUsed=0x00000004,AlwaysUpdate=0x00000008,NeverUpdate=0x0000000C}}
namespace bConnect.Endpoint {public enum UserJobOptions:uint{AlwaysExecute=0x00000000,NeverExecute=0x00000010,ExecuteForPrimaryUser=0x00000030}}
namespace bConnect.Endpoint {public enum ComplianceState{Unknown=0,Compliant=1,Info=2,Warning=3,Severe=4,Inactive=5}}
namespace bConnect.Job {public enum EndpointCategory{Any=-1,Unknown,MicrosoftWindows,GoogleAndroid,AppleIOS,AppleMac,WindowsPhone}}
namespace bConnect.Job {[System.Flags]public enum Options{WOL=0x00000001,CancelOnError=0x00000002,Passive=0x00000004,FinishScreensaver=0x00000008,FinishShutdown=0x00000010,InformationAlways=0x00010000,LogoffUsers=0x00020000,ForceLogoff=0x00040000,InformationHide=0x00080000,UserDelayable=0x00200000,UserCancelable=0x00400000}}
namespace bConnect.Job {public enum State{Unknown=-1,Assigned,Running,FinishedSuccess,FinishedError,FinishedCanceled,ReScheduled,WaitingForUser,RequirementsNotMet,Downloading,SkippedDueToIncompatibility}}
namespace bConnect.Job {public enum Action{Start,Stop,Resume}}
namespace bConnect.Application {public enum SecurityContext{AnyUser,InstallUser,LocalInstallUser,LocalSystem,LoggedOnUser,RegisteredUser,SpecifiedUser}}
namespace bConnect.Application {public enum ValidForOS{NT4,Windows2000,WindowsXP,WindowsVista,Windows7,Windows8,Windows10,WindowsServer2003,WindowsServer2008,WindowsServer2008R2,WindowsServer2012,WindowsXP_x64,WindowsVista_x64,Windows7_x64,Windows8_x64,Windows10_x64,Windows11_x64,WindowsServer2003_x64,WindowsServer2008_x64,WindowsServer2008R2_x64,WindowsServer2012_x64,WindowsServer2016_x64,WindowsServer2019_x64,WindowsServer2022_x64}}
namespace bConnect.Application {public enum FileType{FolderWithSubFolders,SingleFolder,File}}
namespace bConnect.Application {public enum RebootBehaviour{NoReboot,Reboot,AppReboot,DeferrableReboot}}
namespace bConnect.Application {public enum VisibleExecution{Silent,NeedsDesktop,VisibleWhenuserLoggedOn}}
namespace bConnect.Application {public enum IconScope{App,Inventory}}
namespace bConnect.Application {public enum DependencyType{InstallBeforeIfNotInstalled,AlwaysInstallAfterwards,AlwaysInstallBefore,DeinstallBeforeIfInstalled,ErrorIfNotInstalled,ErrorIfInstalled}}
namespace bConnect.Compliance {public enum State{Unknown=0,Compliant=1,NotCompliantInfo=2,NotCompliantWarning=3,NotCompliantSevere=4,Inactive=5}}
namespace bConnect.InventoryScan {public enum Type{Unknown,Custom,WMI,Hardware}}
namespace bConnect.SearchResult {public enum Type{Unknown=0,WindowsEndpoint=1,AndroidEndpoint=2,iOSEndpoint=3,MacEndpoint=4,WindowsPhoneEndpoint=5,WindowsJob=6,BmsNetJob=7,OrgUnit=8,DynamicGroup=9,StaticGroup=10,Application=11,App=12,NetworkEndpoint=16,ADObject=17}}
namespace bConnect.Search {public enum Type{Endpoint,Job,OrgUnit,Group,Software,ADObject}}
namespace bConnect.BootEnvironment {public enum Type{Unknown,DOS,WinPE,WinPE_UEFI,Custom}}
namespace bConnect.Server {public enum ExecutionState{Unknown=0,Stopped=1,StoppedNotConfigured=2,Starting=3,Running=4,RunningNotConfigured=5,MaintenanceMode=6,Warning=7,Stopping=8,RestartRequired=9,NotLicensed=10,RunningNotLicensed=11}}
